test_color_name_to_hex (__main__.TestExercice) ... ERROR
test_compute_mse (__main__.TestExercice) ... FAIL
test_create_list (__main__.TestExercice) ... FAIL
test_list_to_dict (__main__.TestExercice) ... ok

======================================================================
ERROR: test_color_name_to_hex (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 34, in test_color_name_to_hex
    output = [exercice.color_name_to_hex(v) for v in colors]
  File "test_exercice.py", line 34, in <listcomp>
    output = [exercice.color_name_to_hex(v) for v in colors]
  File "/home/runner/work/c04-ch6-exercices-2-fresayu/c04-ch6-exercices-2-fresayu/exercice.py", line 18, in color_name_to_hex
    hexa = [(i,color.cnames[i]) for i in colors]
  File "/home/runner/work/c04-ch6-exercices-2-fresayu/c04-ch6-exercices-2-fresayu/exercice.py", line 18, in <listcomp>
    hexa = [(i,color.cnames[i]) for i in colors]
NameError: name 'color' is not defined

======================================================================
FAIL: test_compute_mse (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 65, in test_compute_mse
    'Erreur dans le calcul des MSE'
AssertionError: {} != {'LR': 220.6, 'DNN': 14.0, 'RF': 1681.8}
- {}
+ {'DNN': 14.0, 'LR': 220.6, 'RF': 1681.8} : Erreur dans le calcul des MSE

======================================================================
FAIL: test_create_list (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 51, in test_create_list
    'Mauvaise reponse'
AssertionError: Lists differ: [] != [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,[57248 chars]9999]

Second list contains 9664 additional elements.
First extra element 0:
0

Diff is 86292 characters long. Set self.maxDiff to None to see it. : Mauvaise reponse

----------------------------------------------------------------------
Ran 4 tests in 0.069s

FAILED (failures=2, errors=1)
